MercuriChat/config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'users#index'
  get 'index'   => 'users#index', to: redirect('/')
  get 'register' => 'users#register', as: :register
  get 'index_debug' => 'users#index1', as: :index_debug
  get 'sign_in'  => 'users#sign_in', as: :'sign_in'
  get 'about'    => 'users#about', as: :about
  get 'team'     => 'users#team', as: :team
  get 'dashboard'     => 'chat#dashboard', as: :dashboard
  get 'group_chat' => 'chat#group_chat', as: :group_chat
  get 'help' => 'chat#help', as: :help
  get 'sign_out' => 'users#sign_out', as: :sign_out
  get 'loadmore' => 'chat#loadmore', as: :loadmore  

end

MercuriChat/app/models/user.rb
class User < ActiveRecord::Base
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :chatlog_entries
  has_many :chats, :through => :chatlog_entries
  has_and_belongs_to_many :group_chats
  has_attached_file :avatar, styles: {medium: "300x300>", thumb: "100x100>"}
  #validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  #Straight from Bcrypt Github docs
  # users.password_hash in the database is a :string
  include BCrypt

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
end

MercuriChat/app/controllers/users_controller.rb
require 'bcrypt'

class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  # before_filter :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def index1
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.where(first_name: params[:find_friend].split[0], last_name: params[:find_friend].split[1]).take if params[:find_friend]
    @user = User.find(params[:id]) if !params[:find_friend]

    if request.xhr?
      me = User.find(session[:user])
      #Create friendship unless it exists.
      friend_request = me.friendships.build(:friend_id => @user.id) unless me.friendships.where(friend_id: @user.id).take
      if friend_request.save
        #Friend added message.
      else
        #Friend not added message.
      end
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    # Creates a new user:
    @user = User.new(user_params)
    @user.password = params[:password][:password]

    respond_to do |format|
      if @user.save
        # Referenced from: http://guides.rubyonrails.org/action_mailer_basics.html#sending-emails
        # Delivers "welcome email" to newly registered users:
        # UserMailer.welcome_email(@user).deliver_later

        # Initializes the session's user with @user.id:
        log_in @user

        # Redirects to the user's dashboard:
        format.html { redirect_to dashboard_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: dashboard_path }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        # Referenced from: https://www.railstutorial.org/book/log_in_log_out
        flash.now[:danger] = 'Invalid email/password combination'
        # render 'new'
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def register
    @user = User.new
  end #register

  def sign_in
    check_login(params) if params[:inputUN]
    # For debugging purposes:
    puts
    puts
    puts "*******************"
    puts "In sign_in: #{params}"
    puts "*******************"
    puts
  end

  # Referenced from: https://www.railstutorial.org/book/log_in_log_out
  # Sets the session's user to the user passed to it:
  def log_in(user)
    session[:user] = user.id
  end

  # Referenced from: https://www.railstutorial.org/book/log_in_log_out
  # Logs out the current user.
  def sign_out
    session[:user] = nil
    redirect_to index_path
  end

  # 
  def is_zero?(index)
    if index == 0
      return true
    else 
      return false
    end
  end

  # Referenced from: https://www.railstutorial.org/book/log_in_log_out
  # Checks to see if the user is currently logged on.
  def signed_in? (user)
    me = User.find(session[:user])

    # For debugging:
    puts
    puts
    puts "****************************"
    puts "Me:   #{me}"
    puts "User: #{user}"
    puts "****************************"
    puts
    puts

    if me != user
      return false
    else
      return true
    end
  end

  # Validates if a user has signed in:
  def check_login(params)
    # For debugging purposes:
    puts
    puts
    puts "*******************"
    puts "#{params}"
    puts "*******************"
    puts

    @user = User.where(email: params[:inputUN]).take
    if @user && @user.password && @user.password == params[:inputPW]
      #Set their session variable to their id. Session variables provide memory to the stateless
      #web. At any time the clients browser accesses session[user], it obtains his public key in
      #the database, a unique identifier which allows the browser to always know who it is.
      log_in @user
      redirect_to dashboard_path
    else
      puts "failed"
      puts params
      print "USER: "
      print "Password Correct ?: "
      puts @user.password == params[:inputPW] if @user
      print "Username: "
      puts params[:inputUN]
      puts params[:password]
      # NOTE: I got errors when I had line 92.
      # puts @user.password == params[:inputPW] if @user.password && params[:inputPW]
      session[:error] = "Incorrect username or password. Please try again."
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password_hash, :password_salt)
  end
end

MercuriChat/app/views/users/about.html.erb
<!DOCTYPE html>
<!--
    File:   http://www.cs.uml.edu/~eseto/Data_Communications_II/about.html
    91.414 Data Communications II Project (MercuriChat)
    Emily Seto, Undergraduate Computer Science student at UMass Lowell, emily_seto@student.uml.edu
    Copyright (c) 2016 by Emily W. Seto. All rights reserved. May be freely copied or excerpted for
        educational purposes with credit to the author.
    The objective of this first assignment is to create an index for upcoming assignments in GUI.
    Updated by EWS on March 31, 2016 at 12:45 PM
-->
<html lang="en-US">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>MercuriChat - About</title>

		<!-- Latest compiled and minified CSS from Bootstrap: -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

		<!-- CSS customizations included and written by Emily Seto. -->
		<%= stylesheet_link_tag "index.css" %>
	</head>
	<body>
		<!-- Navigation bar information from: http://getbootstrap.com/components/#navbar. -->
		<nav class="navbar navbar-default navbar-static-top">
			<div class="container-fluid">
				<!-- Brand and toggle get grouped together for better mobile display. -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Toggle navigation.</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="index.html">MercuriChat</a>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling. -->
				<div class="collapse navbar-collapse" id="navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="register.html">Get Started</a></li>
						<li><a href="sign-in.html">Sign In</a></li>
						<li class="active"><a href="#">About</a></li>
						<li><a href="team.html">The Team</a></li>
					</ul>
				</div>
			</div>
		</nav><!-- End of navigation bar. -->

		<!-- Beginning of the "About" portion -->
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-md-offset-6">
					<p>About the application here.</p>
				</div>
			</div>
		</div>
	</body>
</html>

MercuriChat/app/views/users/show.html.erb
<!DOCTYPE html>
<!--
    File:   http://www.cs.uml.edu/~eseto/Data_Communications_II/show.html.erb
    91.414 Data Communications II Project (MercuriChat)
    Emily Seto, Undergraduate Computer Science student at UMass Lowell, emily_seto@student.uml.edu
    Copyright (c) 2016 by Emily W. Seto. All rights reserved. May be freely copied or excerpted for
        educational purposes with credit to the author.
    The objective of this first assignment is to create an index for upcoming assignments in GUI.
    Updated by EWS on April 17th, 2016 at 3:26 AM
-->
<html lang="en-US">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<%= javascript_include_tag "dashboard" %>
	<title>MercuriChat</title>

	<!-- Linking stylesheets and scripts: -->
	<%= stylesheet_link_tag "index" %>
  	<%= javascript_include_tag "application" %>
  	<%= javascript_include_tag "dashboard" %>

</head>
<body>
<!-- Navigation bar information from: http://getbootstrap.com/components/#navbar. -->
<nav class="navbar navbar-default navbar-static-top">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped together for better mobile display. -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation.</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">MercuriChat</a>
		</div>
		<ul class="nav navbar-nav navbar-right">
			<li><%= link_to "Dashboard", {controller: "chat", action: "dashboard", id: session[:user]}, method: "get" %></li>
        	<li><%= link_to "My Profile", {controller: "users", action: "show", id: session[:user]}, method: "get" %></li>
        	<li><%= link_to "Sign Out", {controller: "users", action: "sign_out"} %></li>
        	<li class="<%= 'active' if params[:controller] == 'dashboard_controller' %>"><a href="help">?</a></li>
      	</ul>
			<!-- Will eventually allow users to search for other people using the client: -->
			<!--form class="navbar-form navbar-right" action=" " method=""-->
			<%= form_tag({controller: "users", action: "show", id: "id"}, method: "get", class: "navbar-form navbar-right") do %>
			<div class="searchbox">
        	<%= text_field_tag "find_friend", nil, class: "form-control", :placeholder => "Search..." %>
		    </div>
			<% end %>
			<!--/form-->
		</div>
	</div>
</nav><!-- End of navigation bar. -->

<!-- Beginning of cover page. -->
<div class="container-fluid">
	<div class="row">
		<!-- Beginning of profile here: -->
		<div class="col-md-6 col-md-offset-3 profile">
			<div class="row">
				<div class="col-md-12" id="usr-profile">
					<center>
						<img src="#" class="img-circle" />
						<h1>
							<strong>
								<%= @user.first_name %>
								<%= @user.last_name %>
							</strong>
						</h1>
						<p class="large">
							<strong>Email Address:</strong>
							<%= @user.email %>
						</p>

<!-- Checks of user is signed in for certain actions: -->
<% if signed_in?(@user) %>
	<!--Avatar code straight from official documentation. -->
	Upload Avatar:
	<%= simple_form_for @user, method: "get", url: users_path do |form| %>
    	<%= form.input :avatar, as: :file %>
    	<%= form.submit "Upload Avatar" %>
	<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<!-- Else, allow the option to add a friend. 
	It will return NIL if the friend has already been added. -->
<% else %>
<%= button_to "Add Friend", user_path(@user.id), method: "get", remote: true %>
<% end %><!-- End of if-else block. -->

					</center>
				</div>
			</div>
		</div><!-- End of "Profile" panel here. -->
	</div>
</div>

</body>
</html>

<!--<p id="notice"><%= notice %></p>-->